#!/bin/bash

PATH="/bin:/sbin:/usr/bin:/usr/sbin:${PATH}"; export PATH
LC_ALL="en_US.UTF-8"; export LC_ALL

TPUT=`which tput`
RED=`$TPUT setaf 1`
GREEN=`$TPUT setaf 2`
YELLOW=`$TPUT setaf 3`
NORMAL=`$TPUT op`

EXIT_FAILURE="1"
DSH_CONFDIR=$HOME/.dsh

PKGDIR="/var/pkg"

if [ -r $HOME/.deployrc ]; then
  . $HOME/.deployrc
fi

errx() {
  local message="$*"
  echo $message${RED}...terminating.${NORMAL}
  exit 1
}

exitf() {
  exit $EXIT_FAILURE
}

isnull() {
  local retval="1"
  local variable="$1"

  if [ "$variable" = "" ]; then retval="0"; fi

  return $retval
}

groupname_exists() {
  local groupname=$1
  local retval="0"

  if [ -r $DSH_CONFDIR/group/$groupname ]; then
    retval="1"
  fi

  return $retval
}

execute_concurrent() {
  local groupname=$1
  shift
  local command="$*"

  if groupname_exists $groupname; then
    echo "groupname \"$groupname\" doesn't exists"
    exitf
  fi

  pre=
  if [ x"$DRYRUN" != x ]; then
    pre="echo "
  fi

  $pre dsh -M -c -g $groupname -- "$command"
}

execute_consistent() {
  local groupname=$1
  shift
  local command="$*"

  if groupname_exists $groupname; then
    echo "groupname \"$groupname\" does not exist"
    exitf
  fi

  pre=
  if [ x"$DRYRUN" != x ]; then
    pre="echo "
  fi

  $pre dsh -M -g $groupname -- "$command"
}

execute_once() {
  local groupname=$1
  shift
  local command="$*"

  if groupname_exists $groupname; then
    echo "groupname \"$groupname\" does not exist"
    exitf
  fi

  machine=`head -1 $DSH_CONFDIR/group/$groupname`

  pre=
  if [ x"$DRYRUN" != x ]; then
    pre="echo "
  fi

  $pre dsh -M -m $machine -- "$command"
}

verbose() {
  local retval

  case "$VERBOSE" in
    0|[nN][oO]) retval=1;;
    *)          retval=0;;
  esac

  return $retval
}

logging() {
  if verbose; then
    cat -
  else
    cat - > /dev/null
  fi
}
