<?php
$this->encodingSystem['defaultProfile'] = 'od';
$this->encodingSystem['video']['od'] = array( // ok definition
    'name' => 'od.flv',
    'format' => 'flv',
    'video' => array(
        'codec' => 'h264',
        'encoder' => 'libx264',
        'bitrate' => 250,
        //'profile' => 'libx264-normal',
        'params' => array(
            'coder' => '1',
            'flags' => '+loop',
            'cmp' => '+chroma',
            'partitions' => '+parti8x8+parti4x4+partp8x8+partb8x8',
            'me_method' => 'hex',
            'subq' => '6',
            'me_range' => '16',
            'g' => '250',
            'keyint_min' => '25',
            'sc_threshold' => '40',
            'i_qfactor' => '0.71',
            'b_strategy' => '1',
            'qcomp' => '0.6',
            'qmin' => '10',
            //'qmax' => '51',
            'qdiff' => '4',
            'bf' => '4',
            'refs' => '2',
            'directpred' => '3',
            'trellis' => '0',
            'flags2' => '+bpyramid+wpred+dct8x8+fastpskip',
        ),
        'multipass' => false,
        'dimensions' => array(
            'width' => 640,
            'height' => 360,
        ),
    ),
    'audio' => array(
        'codec' => 'aac',
        'encoder' => 'libfaac',
        'sample_rate' => 44100,
    ),
);

$this->encodingSystem['video']['sd'] = array( // standart definition
    'name' => 'sd.flv',
    'format' => 'flv',
    'video' => array(
        'codec' => 'h264',
        'encoder' => 'libx264',
        'bitrate' => 500,
        //'profile' => 'libx264-normal',
                'params' => array(
            'coder' => '1',
            'flags' => '+loop',
            'cmp' => '+chroma',
            'partitions' => '+parti8x8+parti4x4+partp8x8+partb8x8',
            'me_method' => 'hex',
            'subq' => '6',
            'me_range' => '16',
            'g' => '250',
            'keyint_min' => '25',
            'sc_threshold' => '40',
            'i_qfactor' => '0.71',
            'b_strategy' => '1',
            'qcomp' => '0.6',
            'qmin' => '10',
            //'qmax' => '51',
            'qdiff' => '4',
            'bf' => '4',
            'refs' => '2',
            'directpred' => '3',
            'trellis' => '0',
            'flags2' => '+bpyramid+wpred+dct8x8+fastpskip',
        ),
        'multipass' => false,
        'dimensions' => array(
            'width' => 640,
            'height' => 360,
        ),
    ),
    'audio' => array(
        'codec' => 'aac',
        'encoder' => 'libfaac',
        'sample_rate' => 44100,
    ),
);
 
$this->encodingSystem['video']['hd'] = array( // high definition 
    'name' => 'hd.mp4',
    'format' => 'mp4',
    'video' => array(
        'codec' => 'h264',
        'encoder' => 'libx264',
        //'profile' => 'libx264-hq',
        'params' => array(
            'coder' => '1',
            'flags' => '+loop',
            'cmp' => '+chroma',
            'partitions' => '+parti8x8+parti4x4+partp8x8+partb8x8',
            'me_method' => 'umh',
            'subq' => '8',
            'me_range' => '16',
            'g' => '250',
            'keyint_min' => '25',
            'sc_threshold' => '40',
            'i_qfactor' => '0.71',
            'b_strategy' => '2',
            'qcomp' => '0.6',
            'qmin' => '10',
            //'qmax' => '51',
            'qdiff' => '4',
            'bf' => '4',
            'refs' => '4',
            'directpred' => '3',
            'trellis' => '1',
            'flags2' => '+bpyramid+wpred+mixed_refs+dct8x8+fastpskip',
        ),
        'bitrate' => 2000,
        'multipass' => false,
        'dimensions' => array(
            'width' => 1280,
            'height' => 720,
        ),
    ),
    'audio' => array(
        'codec' => 'aac',
        'encoder' => 'libfaac',
        'sample_rate' => 44100,
    ),       
);

$this->encodingSystem['thumbnails']['count'] = 5;
$this->encodingSystem['tmp'] = '/var/tmp/encoding/';
$this->encodingSystem['ffmpegLocationDir'] = '/var/tmp/ffmpeg/';