#!/bin/sh

PATH="/bin:/sbin:/usr/bin:/usr/sbin:${PATH}"; export PATH
LC_ALL="en_US.UTF-8"; export LC_ALL

TPUT=`which tput`
RED=`$TPUT setaf 1`
GREEN=`$TPUT setaf 2`
YELLOW=`$TPUT setaf 3`
NORMAL=`$TPUT op`

EXIT_FAILURE="1"
DSH_CONFDIR=$HOME/.dsh

DEPLOY_SYSTEM="yes"
REPO="http://build.local/RPMS/noarch"
PKGDIR="/var/pkg"

errx() {
  local message="$*"
  echo $message${RED}...terminating.${NORMAL}
  exit 1
}

exitf() {
  exit $EXIT_FAILURE
}

isnull() {
  local retval="1"
  local variable="$1"

  if [ x$variable == x ]; then retval="0"; fi

  return $retval
}

groupname_exists() {
  local groupname=$1
  local retval="0"

  if [ -r $DSH_CONFDIR/group/$groupname ]; then
    retval="1"
  fi

  return $retval
}

execute_concurrent() {
  local groupname=$1
  shift
  local command="$*"

  if groupname_exists $groupname; then
    echo "groupname \"$groupname\" doesn't exists"
    exitf
  fi

  pre=
  if [ x"$DRYRUN" != x ]; then
    pre="echo "
  fi

  $pre dsh -M -c -g $groupname -- "$command"
}

execute_consistent() {
  local groupname=$1
  shift
  local command="$*"

  if groupname_exists $groupname; then
    echo "groupname \"$groupname\" does not exist"
    exitf
  fi

  pre=
  if [ x"$DRYRUN" != x ]; then
    pre="echo "
  fi

  $pre dsh -M -g $groupname -- "$command"
}

execute_once() {
  local groupname=$1
  shift
  local command="$*"

  if groupname_exists $groupname; then
    echo "groupname \"$groupname\" does not exist"
    exitf
  fi

  machine=`head -1 $DSH_CONFDIR/group/$groupname`

  pre=
  if [ x"$DRYRUN" != x ]; then
    pre="echo "
  fi

  $pre dsh -M -m $machine -- "$command"
}

# vim:set sw=2 ts=2 et syntax=sh:
